name: CI Python NER
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow tensorflow-addons flake8

      - name: Lint code with flake8
        run: |
          flake8 data_generator.py data_preprocessing.py model.py train.py test_data_generator.py

      - name: Run tests
        run: |
          python test_data_generator.py